import { UIWindow, UIElement } from '../types';

export const generateLuaCode = (data: UIWindow): string => {
  const timestamp = new Date().toLocaleTimeString();
  
  let code = `--[[\n    Generated by ToraIsme GUI Builder\n    Time: ${timestamp}\n    \n    Make sure to put this script in autoexec or run via executor.\n]]\n\n`;
  
  // 1. Library Load
  code += `local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/liebertsx/Tora-Library/main/src/library", true))()\n\n`;
  
  // 2. Window Creation
  const safeTitle = data.title.replace(/"/g, '\\"');
  code += `local window = library:CreateWindow("${safeTitle}")\n\n`;

  // 3. Folders and Elements
  data.folders.forEach((folder, folderIndex) => {
    const folderVar = `folder${folderIndex + 1}`;
    const safeFolderName = folder.text.replace(/"/g, '\\"');
    
    code += `--- [ Folder: ${folder.text} ] ---\n`;
    code += `local ${folderVar} = window:AddFolder("${safeFolderName}")\n\n`;

    folder.elements.forEach((element) => {
      const safeText = element.text.replace(/"/g, '\\"');
      
      // Helper to indent logic
      const injectLogic = (defaultLogic: string) => {
        if (element.customLogic && element.customLogic.trim().length > 0) {
            // Indent user logic for readability
            return element.customLogic.split('\n').map(line => `    ${line}`).join('\n');
        }
        return defaultLogic;
      };

      if (element.type === 'Button') {
        const logic = injectLogic(`    -- [ INSERT LOGIC HERE ]\n    print("${safeText} clicked")`);
        code += `${folderVar}:AddButton({ text = "${safeText}", callback = function()\n${logic}\nend })\n`;
      } 
      else if (element.type === 'Toggle') {
        const el = element;
        const logic = injectLogic(`    -- [ INSERT LOGIC HERE ]\n    print("${safeText} is now:", val)`);
        code += `${folderVar}:AddToggle({ text = "${safeText}", flag = "${el.flag}", callback = function(val)\n${logic}\nend })\n`;
      } 
      else if (element.type === 'Slider') {
        const el = element;
        const logic = injectLogic(`    -- [ INSERT LOGIC HERE ]\n    print("${safeText} set to:", val)`);
        code += `${folderVar}:AddSlider({ text = "${safeText}", min = ${el.min}, max = ${el.max}, value = ${el.value}, decimals = ${el.decimals}, callback = function(val)\n${logic}\nend })\n`;
      } 
      else if (element.type === 'Dropdown') {
        const el = element;
        const valuesString = `{${el.values.map(v => `"${v.replace(/"/g, '\\"')}"`).join(', ')}}`;
        const logic = injectLogic(`    -- [ INSERT LOGIC HERE ]\n    print("${safeText} selected:", val)`);
        code += `${folderVar}:AddList({ text = "${safeText}", values = ${valuesString}, open = false, flag = "${el.flag}", callback = function(val)\n${logic}\nend })\n`;
      }
      code += `\n`;
    });
  });

  // 4. Init
  code += `library:Init()`;

  return code;
};